### ISSUE TITLE
library.properties Still Says Version 1.4.2

### ISSUE THREAD

**Issue by abrahamjsimpson** [PaulStoffregen/Encoder#89]
library.properties has not been updated to reflect the release of version 1.4.3. Line 2 still says 
`version=1.4.2`
This should be updated to reflect the current version (1.4.3). As a result of this, the Arduino IDE says that the version right now is 1.4.2.

**Comment by abrahamjsimpson** [comment]
Just noticed that ee9543ed91e294956031d3a86c4f93eef679d471 . Has this really been a problem for that long?

**Comment by TadyTheFish** [comment]
I'm also trying to use the 1.4.3 version in Platformio and it does not exist because of this. I can only load 1.4.2 that does not have the Rap2040 support fixed

**Comment by cattledogGH** [comment]
Getting an update to version 1.4.3 in the Arduino library manager is important because the previous versions have library examples with .pde files, and the latest 2.0.x ide will only open files with .ino extensions.

[https://github.com/arduino/arduino-ide/issues/518](url)

**Comment by PaulStoffregen** [comment]
Hopefully this will solve the problem
https://github.com/PaulStoffregen/Encoder/commit/547fd926261dbdc87eee5b947ef30b4c63993cd3

**Comment by cattledogGH** [comment]
The Arduino IDE library manager is still not showing V1.4.3.  

[https://github.com/arduino/library-registry/blob/main/FAQ.md#why-arent-releases-of-my-library-being-picked-up-by-library-manager](url)

**Comment by bschippers** [comment]
The tag of v1.4.3 still contains library.properties saying it is v1.4.2. I think that's why it's not getting picked up. Can the tag be moved or make a new release? Here's the log from https://downloads.arduino.cc/libraries/logs/github.com/PaulStoffregen/Encoder/

2023/05/01 18:00:59 Scraping https://github.com/PaulStoffregen/Encoder.git
2023/05/01 18:00:59 Checking out tag: 1.3
2023/05/01 18:00:59 Release Encoder:1.3.0 already loaded, skipping
2023/05/01 18:00:59 Checking out tag: 1.4
2023/05/01 18:00:59 Release Encoder:1.4.0 already loaded, skipping
2023/05/01 18:00:59 Checking out tag: 1.4.1
2023/05/01 18:00:59 Release Encoder:1.4.1 already loaded, skipping
2023/05/01 18:00:59 Checking out tag: 1.4.2
2023/05/01 18:00:59 Release Encoder:1.4.2 already loaded, skipping
2023/05/01 18:00:59 Checking out tag: 1.4.3
2023/05/01 18:00:59 Release Encoder:1.4.2 already loaded, skipping

**Comment by ivankravets** [comment]
The same issue with https://registry.platformio.org/libraries/paulstoffregen/Encoder

@PaulStoffregen, could you remove existing https://github.com/PaulStoffregen/Encoder/releases/tag/1.4.3 tag and create the same `1.4.3` from `547fd926261dbdc87eee5b947ef30b4c63993cd3` commit?

**Comment by ivankravets** [comment]
The same issue with the `MCP_CAN_lib ` library by @coryjfowler and the `1.5.1` tag that points to the previous `1.5.0` version.

**Comment by coryjfowler** [comment]
Why on earth am I being notified about this here????  A professional response would be linking me to a detailed process on how to do this correctly.  Instead 4 different people are just saying what the problem is and potentially one person that actually mentioned what to do to correct the problem for *this* repo.  I still don't know why I am being tagged here what so ever.

**Comment by coryjfowler** [comment]
I do this in my absolute free time, so its cool I get to waste it commenting here instead of implementing a solution.  If anyone knows an employer who is closer to my house in Columbus Indiana than a 100 mile to work and a 100 mile drive back home, that would be great.

**Comment by coryjfowler** [comment]
It looks like I released 1.5.1 before I updated library.properties.  The contents of the ZIP are still 1.5.1 regardless.  Is this non-issue an actual issue for someone or something?  I have other things I could be doing that trying to figure out why I am being tagged here.

**Comment by coryjfowler** [comment]
Also this 1.5.1 tag points to https://github.com/coryjfowler/MCP_CAN_lib/releases/tag/1.5.1  1.5.1 ... I'm lost.  Other than that one digit in a text file in the zip.......

**Comment by ivankravets** [comment]
@coryjfowler, sorry for disturbing you. You are in good company here, all of us love open source and invest our valuable time in it.

> A professional response would be linking me to a detailed process
It was provided in my original comment  https://github.com/PaulStoffregen/Encoder/issues/89#issuecomment-1827993230

> Also this 1.5.1 tag points

Could you open the [1.5.1 tag](https://github.com/coryjfowler/MCP_CAN_lib/tree/1.5.1) and click on `library.properties`. Which `version` value do you see?

---------

Solution. Please remove [1.5.1](https://github.com/coryjfowler/MCP_CAN_lib/releases) release and tag. Make a new one from the latest commit 6f1f30ce41e11bd75a8e367b7666399da8ddeea0 ( https://github.com/coryjfowler/MCP_CAN_lib/commits/master )

**Comment by coryjfowler** [comment]
> It looks like I released 1.5.1 before I updated library.properties.
The contents of the source files should be 1.5.1 despite that.  I am absolutely not sure how to fix it, my git-fu is null and every time I try to learn it, it seems more convoluted and pointless than the last time I tried.  I edit via the web interface! LOL

**Comment by coryjfowler** [comment]
@ivankravets  That horizontal bar made me want to interpret the contents below it as a forum signature at first read and I ignored it subconsciously.  Ha!

**Comment by ivankravets** [comment]
Thanks, @coryjfowler! 🙏 

The library has been automatically updated in the PlatformIO Registry https://registry.platformio.org/libraries/coryjfowler/mcp_can

**Comment by PaulStoffregen** [comment]
I edited library.properties to 1.4.4 and released a new 1.4.4 tag.

Hopefully that fully resolves this issue?

**Comment by ivankravets** [comment]
Thanks, @PaulStoffregen. It works now! https://registry.platformio.org/libraries/paulstoffregen/Encoder

The issue can be closed.

**Comment by PaulStoffregen** [comment]
thanks
